name: check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - run: go vet
